### ISSUE TITLE
Add Todo page

### ISSUE THREAD

**Issue by yurubiftin** [yurubiftin/tsktrain#3]

**Comment by yurubiftin** [comment]
The form shoould contain :

- [ ]task name
- [ ] task priority
- [ ] task due date
- [ ] task status
- [ ] task description input
- [ ] task add button
